/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as AuthenticatedRouteImport } from './presentation/routes/_authenticated'
import { Route as RepairRequestEquipmentIdRouteImport } from './presentation/routes/repair-request/$equipmentId'
import { Route as AccountsLoginRouteImport } from './presentation/routes/accounts/login'
import { Route as AuthenticatedManagerRouteImport } from './presentation/routes/_authenticated/manager'
import { Route as AuthenticatedEngineerRouteImport } from './presentation/routes/_authenticated/engineer'
import { Route as AuthenticatedDashboardSparePartsIndexRouteImport } from './presentation/routes/_authenticated/dashboard/spare-parts/index'
import { Route as AuthenticatedDashboardRepairRequestsIndexRouteImport } from './presentation/routes/_authenticated/dashboard/repair-requests/index'
import { Route as AuthenticatedDashboardRepairRequestsRepairRequestIdRouteImport } from './presentation/routes/_authenticated/dashboard/repair-requests/$repairRequestId'
import { Route as AuthenticatedDashboardManagerStatisticsRouteImport } from './presentation/routes/_authenticated/dashboard/manager/statistics'
import { Route as AuthenticatedDashboardManagerSparePartsRouteImport } from './presentation/routes/_authenticated/dashboard/manager/spare-parts'
import { Route as AuthenticatedDashboardManagerSettingsRouteImport } from './presentation/routes/_authenticated/dashboard/manager/settings'
import { Route as AuthenticatedDashboardManagerEquipmentRouteImport } from './presentation/routes/_authenticated/dashboard/manager/equipment'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRequestEquipmentIdRoute =
  RepairRequestEquipmentIdRouteImport.update({
    id: '/repair-request/$equipmentId',
    path: '/repair-request/$equipmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/accounts/login',
  path: '/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEngineerRoute = AuthenticatedEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardSparePartsIndexRoute =
  AuthenticatedDashboardSparePartsIndexRouteImport.update({
    id: '/dashboard/spare-parts/',
    path: '/dashboard/spare-parts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRepairRequestsIndexRoute =
  AuthenticatedDashboardRepairRequestsIndexRouteImport.update({
    id: '/dashboard/repair-requests/',
    path: '/dashboard/repair-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRepairRequestsRepairRequestIdRoute =
  AuthenticatedDashboardRepairRequestsRepairRequestIdRouteImport.update({
    id: '/dashboard/repair-requests/$repairRequestId',
    path: '/dashboard/repair-requests/$repairRequestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerStatisticsRoute =
  AuthenticatedDashboardManagerStatisticsRouteImport.update({
    id: '/dashboard/manager/statistics',
    path: '/dashboard/manager/statistics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerSparePartsRoute =
  AuthenticatedDashboardManagerSparePartsRouteImport.update({
    id: '/dashboard/manager/spare-parts',
    path: '/dashboard/manager/spare-parts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerSettingsRoute =
  AuthenticatedDashboardManagerSettingsRouteImport.update({
    id: '/dashboard/manager/settings',
    path: '/dashboard/manager/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardManagerEquipmentRoute =
  AuthenticatedDashboardManagerEquipmentRouteImport.update({
    id: '/dashboard/manager/equipment',
    path: '/dashboard/manager/equipment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/engineer': typeof AuthenticatedEngineerRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/dashboard/manager/equipment': typeof AuthenticatedDashboardManagerEquipmentRoute
  '/dashboard/manager/settings': typeof AuthenticatedDashboardManagerSettingsRoute
  '/dashboard/manager/spare-parts': typeof AuthenticatedDashboardManagerSparePartsRoute
  '/dashboard/manager/statistics': typeof AuthenticatedDashboardManagerStatisticsRoute
  '/dashboard/repair-requests/$repairRequestId': typeof AuthenticatedDashboardRepairRequestsRepairRequestIdRoute
  '/dashboard/repair-requests': typeof AuthenticatedDashboardRepairRequestsIndexRoute
  '/dashboard/spare-parts': typeof AuthenticatedDashboardSparePartsIndexRoute
}
export interface FileRoutesByTo {
  '/engineer': typeof AuthenticatedEngineerRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/dashboard/manager/equipment': typeof AuthenticatedDashboardManagerEquipmentRoute
  '/dashboard/manager/settings': typeof AuthenticatedDashboardManagerSettingsRoute
  '/dashboard/manager/spare-parts': typeof AuthenticatedDashboardManagerSparePartsRoute
  '/dashboard/manager/statistics': typeof AuthenticatedDashboardManagerStatisticsRoute
  '/dashboard/repair-requests/$repairRequestId': typeof AuthenticatedDashboardRepairRequestsRepairRequestIdRoute
  '/dashboard/repair-requests': typeof AuthenticatedDashboardRepairRequestsIndexRoute
  '/dashboard/spare-parts': typeof AuthenticatedDashboardSparePartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/engineer': typeof AuthenticatedEngineerRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/_authenticated/dashboard/manager/equipment': typeof AuthenticatedDashboardManagerEquipmentRoute
  '/_authenticated/dashboard/manager/settings': typeof AuthenticatedDashboardManagerSettingsRoute
  '/_authenticated/dashboard/manager/spare-parts': typeof AuthenticatedDashboardManagerSparePartsRoute
  '/_authenticated/dashboard/manager/statistics': typeof AuthenticatedDashboardManagerStatisticsRoute
  '/_authenticated/dashboard/repair-requests/$repairRequestId': typeof AuthenticatedDashboardRepairRequestsRepairRequestIdRoute
  '/_authenticated/dashboard/repair-requests/': typeof AuthenticatedDashboardRepairRequestsIndexRoute
  '/_authenticated/dashboard/spare-parts/': typeof AuthenticatedDashboardSparePartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/engineer'
    | '/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/dashboard/manager/equipment'
    | '/dashboard/manager/settings'
    | '/dashboard/manager/spare-parts'
    | '/dashboard/manager/statistics'
    | '/dashboard/repair-requests/$repairRequestId'
    | '/dashboard/repair-requests'
    | '/dashboard/spare-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/engineer'
    | '/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/dashboard/manager/equipment'
    | '/dashboard/manager/settings'
    | '/dashboard/manager/spare-parts'
    | '/dashboard/manager/statistics'
    | '/dashboard/repair-requests/$repairRequestId'
    | '/dashboard/repair-requests'
    | '/dashboard/spare-parts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/engineer'
    | '/_authenticated/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/_authenticated/dashboard/manager/equipment'
    | '/_authenticated/dashboard/manager/settings'
    | '/_authenticated/dashboard/manager/spare-parts'
    | '/_authenticated/dashboard/manager/statistics'
    | '/_authenticated/dashboard/repair-requests/$repairRequestId'
    | '/_authenticated/dashboard/repair-requests/'
    | '/_authenticated/dashboard/spare-parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountsLoginRoute: typeof AccountsLoginRoute
  RepairRequestEquipmentIdRoute: typeof RepairRequestEquipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-request/$equipmentId': {
      id: '/repair-request/$equipmentId'
      path: '/repair-request/$equipmentId'
      fullPath: '/repair-request/$equipmentId'
      preLoaderRoute: typeof RepairRequestEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/login': {
      id: '/accounts/login'
      path: '/accounts/login'
      fullPath: '/accounts/login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engineer': {
      id: '/_authenticated/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AuthenticatedEngineerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/spare-parts/': {
      id: '/_authenticated/dashboard/spare-parts/'
      path: '/dashboard/spare-parts'
      fullPath: '/dashboard/spare-parts'
      preLoaderRoute: typeof AuthenticatedDashboardSparePartsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/repair-requests/': {
      id: '/_authenticated/dashboard/repair-requests/'
      path: '/dashboard/repair-requests'
      fullPath: '/dashboard/repair-requests'
      preLoaderRoute: typeof AuthenticatedDashboardRepairRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/repair-requests/$repairRequestId': {
      id: '/_authenticated/dashboard/repair-requests/$repairRequestId'
      path: '/dashboard/repair-requests/$repairRequestId'
      fullPath: '/dashboard/repair-requests/$repairRequestId'
      preLoaderRoute: typeof AuthenticatedDashboardRepairRequestsRepairRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager/statistics': {
      id: '/_authenticated/dashboard/manager/statistics'
      path: '/dashboard/manager/statistics'
      fullPath: '/dashboard/manager/statistics'
      preLoaderRoute: typeof AuthenticatedDashboardManagerStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager/spare-parts': {
      id: '/_authenticated/dashboard/manager/spare-parts'
      path: '/dashboard/manager/spare-parts'
      fullPath: '/dashboard/manager/spare-parts'
      preLoaderRoute: typeof AuthenticatedDashboardManagerSparePartsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager/settings': {
      id: '/_authenticated/dashboard/manager/settings'
      path: '/dashboard/manager/settings'
      fullPath: '/dashboard/manager/settings'
      preLoaderRoute: typeof AuthenticatedDashboardManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager/equipment': {
      id: '/_authenticated/dashboard/manager/equipment'
      path: '/dashboard/manager/equipment'
      fullPath: '/dashboard/manager/equipment'
      preLoaderRoute: typeof AuthenticatedDashboardManagerEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEngineerRoute: typeof AuthenticatedEngineerRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedDashboardManagerEquipmentRoute: typeof AuthenticatedDashboardManagerEquipmentRoute
  AuthenticatedDashboardManagerSettingsRoute: typeof AuthenticatedDashboardManagerSettingsRoute
  AuthenticatedDashboardManagerSparePartsRoute: typeof AuthenticatedDashboardManagerSparePartsRoute
  AuthenticatedDashboardManagerStatisticsRoute: typeof AuthenticatedDashboardManagerStatisticsRoute
  AuthenticatedDashboardRepairRequestsRepairRequestIdRoute: typeof AuthenticatedDashboardRepairRequestsRepairRequestIdRoute
  AuthenticatedDashboardRepairRequestsIndexRoute: typeof AuthenticatedDashboardRepairRequestsIndexRoute
  AuthenticatedDashboardSparePartsIndexRoute: typeof AuthenticatedDashboardSparePartsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEngineerRoute: AuthenticatedEngineerRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedDashboardManagerEquipmentRoute:
    AuthenticatedDashboardManagerEquipmentRoute,
  AuthenticatedDashboardManagerSettingsRoute:
    AuthenticatedDashboardManagerSettingsRoute,
  AuthenticatedDashboardManagerSparePartsRoute:
    AuthenticatedDashboardManagerSparePartsRoute,
  AuthenticatedDashboardManagerStatisticsRoute:
    AuthenticatedDashboardManagerStatisticsRoute,
  AuthenticatedDashboardRepairRequestsRepairRequestIdRoute:
    AuthenticatedDashboardRepairRequestsRepairRequestIdRoute,
  AuthenticatedDashboardRepairRequestsIndexRoute:
    AuthenticatedDashboardRepairRequestsIndexRoute,
  AuthenticatedDashboardSparePartsIndexRoute:
    AuthenticatedDashboardSparePartsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountsLoginRoute: AccountsLoginRoute,
  RepairRequestEquipmentIdRoute: RepairRequestEquipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
