/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as AuthenticatedRouteImport } from './presentation/routes/_authenticated'
import { Route as RepairRequestEquipmentIdRouteImport } from './presentation/routes/repair-request/$equipmentId'
import { Route as AccountsLoginRouteImport } from './presentation/routes/accounts/login'
import { Route as AuthenticatedManagerRouteImport } from './presentation/routes/_authenticated/manager'
import { Route as AuthenticatedEngineerRouteImport } from './presentation/routes/_authenticated/engineer'
import { Route as AuthenticatedSparePartsIndexRouteImport } from './presentation/routes/_authenticated/spare-parts/index'
import { Route as AuthenticatedRepairRequestsIndexRouteImport } from './presentation/routes/_authenticated/repair-requests/index'
import { Route as AuthenticatedRepairRequestsRepairRequestIdRouteImport } from './presentation/routes/_authenticated/repair-requests/$repairRequestId'
import { Route as AuthenticatedManagerStatisticsRouteImport } from './presentation/routes/_authenticated/manager/statistics'
import { Route as AuthenticatedManagerSparePartsRouteImport } from './presentation/routes/_authenticated/manager/spare-parts'
import { Route as AuthenticatedManagerSettingsRouteImport } from './presentation/routes/_authenticated/manager/settings'
import { Route as AuthenticatedManagerEquipmentRouteImport } from './presentation/routes/_authenticated/manager/equipment'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRequestEquipmentIdRoute =
  RepairRequestEquipmentIdRouteImport.update({
    id: '/repair-request/$equipmentId',
    path: '/repair-request/$equipmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/accounts/login',
  path: '/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEngineerRoute = AuthenticatedEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSparePartsIndexRoute =
  AuthenticatedSparePartsIndexRouteImport.update({
    id: '/spare-parts/',
    path: '/spare-parts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairRequestsIndexRoute =
  AuthenticatedRepairRequestsIndexRouteImport.update({
    id: '/repair-requests/',
    path: '/repair-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairRequestsRepairRequestIdRoute =
  AuthenticatedRepairRequestsRepairRequestIdRouteImport.update({
    id: '/repair-requests/$repairRequestId',
    path: '/repair-requests/$repairRequestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerStatisticsRoute =
  AuthenticatedManagerStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerSparePartsRoute =
  AuthenticatedManagerSparePartsRouteImport.update({
    id: '/spare-parts',
    path: '/spare-parts',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerSettingsRoute =
  AuthenticatedManagerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerEquipmentRoute =
  AuthenticatedManagerEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/engineer': typeof AuthenticatedEngineerRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/manager/equipment': typeof AuthenticatedManagerEquipmentRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/spare-parts': typeof AuthenticatedManagerSparePartsRoute
  '/manager/statistics': typeof AuthenticatedManagerStatisticsRoute
  '/repair-requests/$repairRequestId': typeof AuthenticatedRepairRequestsRepairRequestIdRoute
  '/repair-requests': typeof AuthenticatedRepairRequestsIndexRoute
  '/spare-parts': typeof AuthenticatedSparePartsIndexRoute
}
export interface FileRoutesByTo {
  '/engineer': typeof AuthenticatedEngineerRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/manager/equipment': typeof AuthenticatedManagerEquipmentRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/spare-parts': typeof AuthenticatedManagerSparePartsRoute
  '/manager/statistics': typeof AuthenticatedManagerStatisticsRoute
  '/repair-requests/$repairRequestId': typeof AuthenticatedRepairRequestsRepairRequestIdRoute
  '/repair-requests': typeof AuthenticatedRepairRequestsIndexRoute
  '/spare-parts': typeof AuthenticatedSparePartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/engineer': typeof AuthenticatedEngineerRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/_authenticated/manager/equipment': typeof AuthenticatedManagerEquipmentRoute
  '/_authenticated/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/_authenticated/manager/spare-parts': typeof AuthenticatedManagerSparePartsRoute
  '/_authenticated/manager/statistics': typeof AuthenticatedManagerStatisticsRoute
  '/_authenticated/repair-requests/$repairRequestId': typeof AuthenticatedRepairRequestsRepairRequestIdRoute
  '/_authenticated/repair-requests/': typeof AuthenticatedRepairRequestsIndexRoute
  '/_authenticated/spare-parts/': typeof AuthenticatedSparePartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/engineer'
    | '/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/manager/equipment'
    | '/manager/settings'
    | '/manager/spare-parts'
    | '/manager/statistics'
    | '/repair-requests/$repairRequestId'
    | '/repair-requests'
    | '/spare-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/engineer'
    | '/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/manager/equipment'
    | '/manager/settings'
    | '/manager/spare-parts'
    | '/manager/statistics'
    | '/repair-requests/$repairRequestId'
    | '/repair-requests'
    | '/spare-parts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/engineer'
    | '/_authenticated/manager'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/_authenticated/manager/equipment'
    | '/_authenticated/manager/settings'
    | '/_authenticated/manager/spare-parts'
    | '/_authenticated/manager/statistics'
    | '/_authenticated/repair-requests/$repairRequestId'
    | '/_authenticated/repair-requests/'
    | '/_authenticated/spare-parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountsLoginRoute: typeof AccountsLoginRoute
  RepairRequestEquipmentIdRoute: typeof RepairRequestEquipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-request/$equipmentId': {
      id: '/repair-request/$equipmentId'
      path: '/repair-request/$equipmentId'
      fullPath: '/repair-request/$equipmentId'
      preLoaderRoute: typeof RepairRequestEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/login': {
      id: '/accounts/login'
      path: '/accounts/login'
      fullPath: '/accounts/login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engineer': {
      id: '/_authenticated/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AuthenticatedEngineerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spare-parts/': {
      id: '/_authenticated/spare-parts/'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof AuthenticatedSparePartsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repair-requests/': {
      id: '/_authenticated/repair-requests/'
      path: '/repair-requests'
      fullPath: '/repair-requests'
      preLoaderRoute: typeof AuthenticatedRepairRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repair-requests/$repairRequestId': {
      id: '/_authenticated/repair-requests/$repairRequestId'
      path: '/repair-requests/$repairRequestId'
      fullPath: '/repair-requests/$repairRequestId'
      preLoaderRoute: typeof AuthenticatedRepairRequestsRepairRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/statistics': {
      id: '/_authenticated/manager/statistics'
      path: '/statistics'
      fullPath: '/manager/statistics'
      preLoaderRoute: typeof AuthenticatedManagerStatisticsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/spare-parts': {
      id: '/_authenticated/manager/spare-parts'
      path: '/spare-parts'
      fullPath: '/manager/spare-parts'
      preLoaderRoute: typeof AuthenticatedManagerSparePartsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/settings': {
      id: '/_authenticated/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthenticatedManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/equipment': {
      id: '/_authenticated/manager/equipment'
      path: '/equipment'
      fullPath: '/manager/equipment'
      preLoaderRoute: typeof AuthenticatedManagerEquipmentRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
  }
}

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerEquipmentRoute: typeof AuthenticatedManagerEquipmentRoute
  AuthenticatedManagerSettingsRoute: typeof AuthenticatedManagerSettingsRoute
  AuthenticatedManagerSparePartsRoute: typeof AuthenticatedManagerSparePartsRoute
  AuthenticatedManagerStatisticsRoute: typeof AuthenticatedManagerStatisticsRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerEquipmentRoute: AuthenticatedManagerEquipmentRoute,
  AuthenticatedManagerSettingsRoute: AuthenticatedManagerSettingsRoute,
  AuthenticatedManagerSparePartsRoute: AuthenticatedManagerSparePartsRoute,
  AuthenticatedManagerStatisticsRoute: AuthenticatedManagerStatisticsRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedEngineerRoute: typeof AuthenticatedEngineerRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedRepairRequestsRepairRequestIdRoute: typeof AuthenticatedRepairRequestsRepairRequestIdRoute
  AuthenticatedRepairRequestsIndexRoute: typeof AuthenticatedRepairRequestsIndexRoute
  AuthenticatedSparePartsIndexRoute: typeof AuthenticatedSparePartsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEngineerRoute: AuthenticatedEngineerRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedRepairRequestsRepairRequestIdRoute:
    AuthenticatedRepairRequestsRepairRequestIdRoute,
  AuthenticatedRepairRequestsIndexRoute: AuthenticatedRepairRequestsIndexRoute,
  AuthenticatedSparePartsIndexRoute: AuthenticatedSparePartsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountsLoginRoute: AccountsLoginRoute,
  RepairRequestEquipmentIdRoute: RepairRequestEquipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
