/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as RepairRequestEquipmentIdRouteImport } from './presentation/routes/repair-request/$equipmentId'
import { Route as AccountsLoginRouteImport } from './presentation/routes/accounts/login'
import { Route as EngineerDashboardRepairRequestsIndexRouteImport } from './presentation/routes/engineer/dashboard/repair-requests/index'
import { Route as EngineerDashboardRepairRequestsRepairRequestIdRouteImport } from './presentation/routes/engineer/dashboard/repair-requests/$repairRequestId'

const RepairRequestEquipmentIdRoute =
  RepairRequestEquipmentIdRouteImport.update({
    id: '/repair-request/$equipmentId',
    path: '/repair-request/$equipmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/accounts/login',
  path: '/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerDashboardRepairRequestsIndexRoute =
  EngineerDashboardRepairRequestsIndexRouteImport.update({
    id: '/engineer/dashboard/repair-requests/',
    path: '/engineer/dashboard/repair-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EngineerDashboardRepairRequestsRepairRequestIdRoute =
  EngineerDashboardRepairRequestsRepairRequestIdRouteImport.update({
    id: '/engineer/dashboard/repair-requests/$repairRequestId',
    path: '/engineer/dashboard/repair-requests/$repairRequestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/engineer/dashboard/repair-requests/$repairRequestId': typeof EngineerDashboardRepairRequestsRepairRequestIdRoute
  '/engineer/dashboard/repair-requests': typeof EngineerDashboardRepairRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/engineer/dashboard/repair-requests/$repairRequestId': typeof EngineerDashboardRepairRequestsRepairRequestIdRoute
  '/engineer/dashboard/repair-requests': typeof EngineerDashboardRepairRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accounts/login': typeof AccountsLoginRoute
  '/repair-request/$equipmentId': typeof RepairRequestEquipmentIdRoute
  '/engineer/dashboard/repair-requests/$repairRequestId': typeof EngineerDashboardRepairRequestsRepairRequestIdRoute
  '/engineer/dashboard/repair-requests/': typeof EngineerDashboardRepairRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/engineer/dashboard/repair-requests/$repairRequestId'
    | '/engineer/dashboard/repair-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/engineer/dashboard/repair-requests/$repairRequestId'
    | '/engineer/dashboard/repair-requests'
  id:
    | '__root__'
    | '/accounts/login'
    | '/repair-request/$equipmentId'
    | '/engineer/dashboard/repair-requests/$repairRequestId'
    | '/engineer/dashboard/repair-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountsLoginRoute: typeof AccountsLoginRoute
  RepairRequestEquipmentIdRoute: typeof RepairRequestEquipmentIdRoute
  EngineerDashboardRepairRequestsRepairRequestIdRoute: typeof EngineerDashboardRepairRequestsRepairRequestIdRoute
  EngineerDashboardRepairRequestsIndexRoute: typeof EngineerDashboardRepairRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repair-request/$equipmentId': {
      id: '/repair-request/$equipmentId'
      path: '/repair-request/$equipmentId'
      fullPath: '/repair-request/$equipmentId'
      preLoaderRoute: typeof RepairRequestEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/login': {
      id: '/accounts/login'
      path: '/accounts/login'
      fullPath: '/accounts/login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/dashboard/repair-requests/': {
      id: '/engineer/dashboard/repair-requests/'
      path: '/engineer/dashboard/repair-requests'
      fullPath: '/engineer/dashboard/repair-requests'
      preLoaderRoute: typeof EngineerDashboardRepairRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/dashboard/repair-requests/$repairRequestId': {
      id: '/engineer/dashboard/repair-requests/$repairRequestId'
      path: '/engineer/dashboard/repair-requests/$repairRequestId'
      fullPath: '/engineer/dashboard/repair-requests/$repairRequestId'
      preLoaderRoute: typeof EngineerDashboardRepairRequestsRepairRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AccountsLoginRoute: AccountsLoginRoute,
  RepairRequestEquipmentIdRoute: RepairRequestEquipmentIdRoute,
  EngineerDashboardRepairRequestsRepairRequestIdRoute:
    EngineerDashboardRepairRequestsRepairRequestIdRoute,
  EngineerDashboardRepairRequestsIndexRoute:
    EngineerDashboardRepairRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
